// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProyecto.Models
{
    public partial class Libro
    {
        public string Isbn { get; set; }
        public int IdGenero { get; set; }
        public string Titulo { get; set; }
        public string Autor { get; set; }
        public int Precio { get; set; }
        public int Stock { get; set; }
    }
}