// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProyecto.Models
{
    public partial class Venta
    {
        public int IdVenta { get; set; }
        public int IdUsuario { get; set; }
        public string Isbn { get; set; }
    }
}